#!/bin/bash

# This file was generated by "backup-homebrew.sh"

failed_items=""

install_homebrew() {
	if ! command -v brew >/dev/null; then
		echo "Installing homebrew..."
		ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  else
      echo "Homebrew already installed"
	fi
}

install_package() {
  echo EXECUTING: brew install $1 $2
  brew install $1 $2
  [ $? -ne 0 ] && $failed_items="$failed_items $1"  # package failed to install.
}

install_cask() {
  echo EXECUTING: brew cask install $1
  brew cask install $1
  [ $? -ne 0 ] && $failed_items="$failed_items $1"  # cask failed to install.
}

install_homebrew

brew tap caskroom/cask
install_package brew-cask ''
install_package git ''
install_cask divvy
install_cask kaleidoscope
install_cask nvalt
install_cask tower
[ ! -z $failed_items ] && echo The following items were failed to install: && echo $failed_items
